name: Create Comment

on:
  issues:
    types: [created, edited]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'xxx'
    steps:
      - name: WeChat Work notification by text
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: "## Issue notification\n
          > **Repository:** <font color=\"comment\">${{ github.repository }}</font> \n
          > **Issue:** <font color=\"comment\">${{ github.event.issue.html_url }}</font> \n
          > **Title:** <font color=\"comment\">${{ github.event.issue.title }}</font>"
          mentioned_list: '["lark","shengyu"]'
